services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jhg\DoctrinePaginationBundle\EventListener\PaginationParamConverterListener:
        tags: ['kernel.event_subscriber']